global:
  storageClass: "longhorn"
  redis:
    password: "Ekfrldndb#3"
persistence:
  enabled: true
  size: 1Gi

#usePassword: false

service:
  ports:
    redis: 6379
  nodePorts:
    redis: ""
  type: NodePort

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
