service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /tmon/longhorn
