service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /tmon/longhorn

longhornManager:
  nodeSelector:
    role: "longhorn"
longhornDriver:
  nodeSelector:
    role: "longhorn"
longhornUI:
  nodeSelector:
    role: "longhorn"

defaultSettings:
  taintToleration: "role=longhorn:NoSchedule"

