
service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultFsType: ext4
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

csi:
  kubeletRootDir: ~
  attacherReplicaCount: 3
  provisionerReplicaCount: 3
  resizerReplicaCount: 3
  snapshotterReplicaCount: 3

defaultSettings:
  defaultDataPath: /tmon/longhorn
  replicaSoftAntiAffinity: false
  defaultReplicaCount: 3
  taintToleration: longhorn=storage:NoSchedule
  systemManagedComponentsNodeSelector: "role:longhorn"

longhornManager:
  tolerations:
  - key: "longhorn"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

longhornDriver:
  tolerations:
  - key: "longhorn"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

longhornUI:
  tolerations:
  - key: "longhorn"
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

