service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /tmon/longhorn

longhornManager:
  nodeSelector:
    role: "longhorn-storage"
longhornDriver:
  nodeSelector:
    role: "longhorn-storage"
longhornUI:
  nodeSelector:
    role: "longhorn-storage"

defaultSettings:
  taintToleration: "role=longhorn-storage:NoSchedule"

