
service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: false
  defaultFsType: ext4
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

csi:
  kubeletRootDir: ~
  attacherReplicaCount: ~
  provisionerReplicaCount: ~
  resizerReplicaCount: ~
  snapshotterReplicaCount: ~

defaultSettings:
  defaultDataPath: /tmon/longhorn
  defaultReplicaCount: ~
#  replicaSoftAntiAffinity: false
#  taintToleration: longhorn=storage:NoSchedule
  systemManagedComponentsNodeSelector: "role:longhorn"

longhornManager:
#  tolerations:
#  - key: "longhorn"
#    operator: "Exists"
#    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

longhornDriver:
#  tolerations:
#  - key: "longhorn"
#    operator: "Exists"
#    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

longhornUI:
#  tolerations:
#  - key: "longhorn"
#    operator: "Exists"
#    effect: "NoSchedule"
  nodeSelector:
   role: "longhorn"

