service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /tmon/longhorn

longhornManager:
  nodeSelector:
    longhorn: "storage"
longhornDriver:
  nodeSelector:
    longhorn: "storage"
longhornUI:
  nodeSelector:
    longhorn: "storage"

