service:
  ui:
    type: NodePort
    nodePort: 30200
  manager:
    type: ClusterIP
    nodePort: ""

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

defaultSettings:
  defaultDataPath: /tmon/longhorn

longhornManager:
  nodeSelector:
    role: "longhorn-node"
longhornDriver:
  nodeSelector:
    role: "longhorn-node"
longhornUI:
  nodeSelector:
    role: "longhorn-node"

