{{- if not .Values.secretConfigName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastalert.fullname" . }}-config
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  elastalert_config: |-
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: false
    run_every:
      seconds: 10
    buffer_time:
      minutes: 15
    es_host: logelk1.tmonc.net
    es_port: 9200
    writeback_index: elastalert_status
    writeback_alias: elastalert_alerts
    alert_time_limit:
      days: 2
