
nodeSelector:
  role: ceph-node

tolerations:
  - effect: NoSchedule
  key: ceph-node
  operator: Exists

csi:
  provisionerTolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  provisionerNodeAffinity: key1=value1,value2; key2=value3

  pluginTolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  pluginNodeAffinity: key1=value1,value2; key2=value3

agent:
  tolerations:
  - key: ceph-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: key1=value1,value2; key2=value3

discover:
  tolerations:
  - key: ceph-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: key1=value1,value2; key2=value3

admissionController:
  tolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  nodeAffinity: key1=value1,value2; key2=value3
