

nodeSelector:
 role: ceph

tolerations:
  - effect: NoSchedule
    key: ceph
    operator: Exists

csi:
  provisionerTolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  provisionerNodeAffinity: role=ceph

  pluginTolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  pluginNodeAffinity: role=ceph

agent:
  toleration: NoSchedule
  tolerationKey: ceph
  tolerations:
  - key: ceph
    operator: Exists
    effect: NoSchedule
  nodeAffinity: role=ceph

discover:
  toleration: NoSchedule
  tolerationKey: ceph
  tolerations:
  - key: ceph
    operator: Exists
    effect: NoSchedule
  nodeAffinity: role=ceph
  podLabels: "role=ceph

admissionController:
  tolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  nodeAffinity: role=ceph
