
nodeSelector:
  ceph: storage

tolerations:
  - effect: NoSchedule
    key: ceph
    operator: Exists

csi:
  provisionerTolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  provisionerNodeAffinity: "ceph=storage"

  pluginTolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  pluginNodeAffinity: "ceph=storage"

agent:
  tolerations:
  - key: ceph
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "ceph=storage"

discover:
  tolerations:
  - key: ceph
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "ceph=storage"

admissionController:
  tolerations:
     - key: ceph
       operator: Exists
       effect: NoSchedule
  nodeAffinity: "ceph=storage"
