
nodeSelector:
  role: ceph-node

tolerations:
  - effect: NoSchedule
    key: ceph-node
    operator: Exists

csi:
  provisionerTolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  provisionerNodeAffinity: "role=ceph-node"

  pluginTolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  pluginNodeAffinity: "role=ceph-node"

agent:
  tolerations:
  - key: ceph-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "role=ceph-node"

discover:
  tolerations:
  - key: ceph-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "role=ceph-node"

admissionController:
  tolerations:
     - key: ceph-node
       operator: Exists
       effect: NoSchedule
  nodeAffinity: "role=ceph-node"
