
nodeSelector:
  role: storage-node

tolerations:
  - effect: NoSchedule
    key: storage-node
    operator: Exists

csi:
  provisionerTolerations:
     - key: storage-node
       operator: Exists
       effect: NoSchedule
  provisionerNodeAffinity: "role=storage-node"

  pluginTolerations:
     - key: storage-node
       operator: Exists
       effect: NoSchedule
  pluginNodeAffinity: "role=storage-node"

agent:
  tolerations:
  - key: storage-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "role=storage-node"

discover:
  tolerations:
  - key: storage-node
    operator: Exists
    effect: NoSchedule
  nodeAffinity: "role=storage-node"

admissionController:
  tolerations:
     - key: storage-node
       operator: Exists
       effect: NoSchedule
  nodeAffinity: "role=storage-node"
