
toolbox:
  enabled: true
  image: rook/ceph:v1.7.5
  tolerations:
  - key: ceph
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ceph
            operator: In
            values:
            - storage

  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: ceph
                operator: In
              values:
              - storage
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: ceph
        operator: Exists
