toolbox:
  enabled: true
  image: rook/ceph:v1.7.5
  tolerations: []
  affinity: {}

cephClusterSpec:
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - ceph
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: ceph
        operator: Exists
