
toolbox:
  enabled: true
  image: rook/ceph:v1.7.5
  tolerations: []
  affinity: {}

  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
              values:
              - ceph-node
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: ceph-node
        operator: Exists
