toolbox:
  enabled: true
  image: rook/ceph:v1.7.5
  tolerations:
  - key: ceph
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - ceph

cephClusterSpec:
  mgr:
    count: 1
  placement:
    all:
      nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - ceph
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: ceph
        operator: Exists

cephFileSystems: []
cephObjectStores: []
