toolbox:
  enabled: true
  image: rook/ceph:v1.7.5
  tolerations: []
  tolerations:
  - key: ceph
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - ceph


cephClusterSpec:
  placement:
    all:
      nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 100
       #requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - ceph
          topologyKey: "kubernetes.io/hostname"
      podAffinity:
      podAntiAffinity:
      topologySpreadConstraints:
      tolerations:
      - key: ceph
        operator: Exists
