grafana:
  persistence:
    enabled: true
  service:
    type: "NodePort"
    nodePort: 30862

prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: ceph-block
          resources:
            requests:
              storage: 10Gi
